### ISSUE TITLE
In Places Unseen french translation

### ISSUE THREAD

**Issue by Indoy** [NPBruce/valkyrie-questdata#35]
Hi !
I began a translation of the scenario you've created.

First of all, are you agree with the idea?
Then i try to be as close as you when creating questlines and atmosphere, but my english is probably not good enough sometimes to catch all the intricacies of English...
However may i send you later a couple of sentences / phrases i've difficulty for?

Thx for reply
Regards
Y.

**Comment by NPBruce** [comment]
Sorry Indoy, this is my development repo.  In Places Unseen has lived here in the past, but isn't maintained here.

You can submit an issue here:
https://github.com/LordPyrex/valkyrie-questdata

Or just use the main Valkyrie page here:
https://github.com/NPBruce/valkyrie/issues

Because LordPyrex is a developer there I can assign the issue.
